name: CI - Build & Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔐 Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🔐 Login to ACR
      - name: ACR Login
        run: az acr login --name aiopsregistry123

      # 🐳 Build Docker Image
      - name: Build Docker Image
        run: docker build -t aiopsregistry123.azurecr.io/ai-campus:latest -f docker/Dockerfile .

      # 📤 Push Docker Image
      - name: Push Docker Image
        run: docker push aiopsregistry123.azurecr.io/ai-campus:latest